# Generated by Django 4.1.1 on 2022-09-22 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': [('can_create_user', 'Can create user')]},
        ),
    ]
