# Generated by Django 4.1.1 on 2022-09-22 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_author_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': [('can_create_author', 'Can create/update/delte author')]},
        ),
    ]
