# Generated by Django 4.1.1 on 2022-09-22 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_author_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_create_book', 'Can create/update/delete book')]},
        ),
    ]
